name: vagas_flutter_web
description: The Elite37 Jobs WebApp in Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0
  go_router: ^6.2.0
  mocktail: ^0.3.0
  dartz: ^0.10.1
  dio: ^5.0.1
  pretty_dio_logger: ^1.1.1
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  bloc_test: ^9.1.1

  vagas_design_system:
    path: ../VAGAS_FLUTTER_DESIGN_SYSTEM/
    # git:
    #   url: https://github.com/elite37oficial/VAGAS_FLUTTER_DESIGN_SYSTEM
    #   ref: feature/login_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
